name: build

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 8
      - name: Build
        run: chmod 777 ./gradlew && ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.0.0
        with:
          name: UsefulPlugin
          path: build/libs/*.jar
